export const REQUEST_DATA = "REQUEST_DATA";
export const RECEIVE_DATA = "RECEIVE_DATA";
export const FORM_FETCHED_DATA = "FORM_FETCHED_DATA";
export const CHANGE_MAP_DATA = "CHANGE_MAP_DATA";
export const RUSSIAN_CITIES_TOGGLE = "RUSSIAN_CITIES_TOGGLE"
export const RUSSIAN_CITIES_SEARCH = "RUSSIAN_CITIES_SEARCH"