export default function(day) {
  let dayString = String(day)

switch (dayString) {
  case '0': return ' дней'
  case '1': return ' день'
  case '2': return ' дня'
  case '3': return ' дня'
  case '4': return ' дня'
  case '5': return ' дней'
  case '6': return ' дней'
  case '7': return ' дней'
  case '8': return ' дней'
  case '9': return ' дней'
  case '10': return ' дней'
  case '11': return ' дней'
  case '12': return ' дней'
  case '13': return ' дней'
  case '14': return ' дней'
  case '15': return ' дней'
  case '16': return ' дней'
  case '17': return ' дней'
  case '18': return ' дней'
  case '19': return ' дней'
  case '20': return ' дней'
  case '21': return ' день'
  case '22': return ' дня'
  case '23': return ' дня'
  case '24': return ' дня'
  case '25': return ' дней'
  case '26': return ' дней'
  case '27': return ' дней'
  case '28': return ' дней'
  case '29': return ' дней'
  case '30': return ' дней'
  case '31': return ' день'
  case '32': return ' дня'
  case '33': return ' дня'
  default: return ' дней'
}
}